### ISSUE TITLE
Install issue on Ubuntu 16.04: error: ‘string’ does not name a type

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [DocCreator/DocCreator#1]
While trying to install on Ubuntu 16.04, I encountered the following problem:

```
In file included from /usr/local/include/tesseract/ltrresultiterator.h:26:0,
                 from /usr/local/include/tesseract/resultiterator.h:26,
                 from /usr/local/include/tesseract/baseapi.h:31,
                 from /home/jbc/DocCreator/software/DocCreator/src/FontGenerator/OCRDialog.cpp:20:
/usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
   static string UTF32ToUTF8(const std::vector<char32>& str32);
          ^
software/DocCreator/CMakeFiles/DocCreator.dir/build.make:1826 : la recette pour la cible « software/DocCreator/CMakeFiles/DocCreator.dir/src/FontGenerator/OCRDialog.cpp.o » a échouée
make[2]: *** [software/DocCreator/CMakeFiles/DocCreator.dir/src/FontGenerator/OCRDialog.cpp.o] Erreur 1
CMakeFiles/Makefile2:256 : la recette pour la cible « software/DocCreator/CMakeFiles/DocCreator.dir/all » a échouée
```

I tried to modify /usr/include/c++/v1/string` as per https://stackoverflow.com/questions/37096062/get-a-basic-c-program-to-compile-using-clang-on-ubuntu-16/38385967#38385967, and even to create a symbolic link with `ln -s /usr/include/libcxxabi/__cxxabi_config.h /usr/include/c++/v1/__cxxabi_config.h`, as suggested in the comments, but I still get this error.

I also tried, as suggested in the Troubleshooting section, to uncomment the line
```
#SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

But, after that, I get another error, 

```
[ 17%] Building CXX object software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/CMakeFiles/lzhamdecomp.dir/lzham_assert.cpp.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h:9:0,
                 from /usr/include/c++/5/cstdint:41,
                 from /usr/include/c++/5/bits/char_traits.h:420,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_core.h:250,
                 from /home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_assert.cpp:3:
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:48:17: error: expected unqualified-id before numeric constant
    const uint8  UINT8_MAX  = 0xFFU;
                 ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:48:17: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:50:17: error: expected unqualified-id before numeric constant
    const uint16 UINT16_MAX = 0xFFFFU;
                 ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:50:17: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:52:17: error: expected unqualified-id before numeric constant
    const uint32 UINT32_MAX = 0xFFFFFFFFU;
                 ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:52:17: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:54:17: error: expected unqualified-id before numeric constant
    const uint64 UINT64_MAX = 0xFFFFFFFFFFFFFFFFULL;    //0xFFFFFFFFFFFFFFFFui64;
                 ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:54:17: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:56:16: error: expected unqualified-id before ‘-’ token
    const int8  INT8_MIN  = -128;
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:56:16: error: expected ‘)’ before ‘-’ token
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:57:16: error: expected unqualified-id before numeric constant
    const int8  INT8_MAX  = 127;
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:57:16: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:58:16: error: expected unqualified-id before ‘-’ token
    const int16 INT16_MIN = -32768;
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:58:16: error: expected ‘)’ before ‘-’ token
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:59:16: error: expected unqualified-id before numeric constant
    const int16 INT16_MAX = 32767;
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:59:16: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:60:16: error: expected unqualified-id before ‘-’ token
    const int32 INT32_MIN = (-2147483647 - 1);
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:60:16: error: expected ‘)’ before ‘-’ token
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:61:16: error: expected unqualified-id before numeric constant
    const int32 INT32_MAX = 2147483647;
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:61:16: error: expected ‘)’ before numeric constant
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:62:16: error: expected unqualified-id before ‘-’ token
    const int64 INT64_MIN = (int64)0x8000000000000000ULL; //(-9223372036854775807i64 - 1);
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:62:16: error: expected ‘)’ before ‘-’ token
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:63:16: error: expected unqualified-id before numeric constant
    const int64 INT64_MAX = (int64)0x7FFFFFFFFFFFFFFFULL; //9223372036854775807i64;
                ^
/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/lzham_types.h:63:16: error: expected ‘)’ before numeric constant
software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/CMakeFiles/lzhamdecomp.dir/build.make:65 : la recette pour la cible « software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/lzhamdecomp/CMakeFiles/lzhamdecomp.dir/lzham_assert.cpp.o » a échouée
```

**Comment by BorisMansencal** [comment]
Hi,
Are you compiling with gcc or clang ?
AFAIK, patching /usr/include/c++/v1/string is only necessary if you are using clang.
Besides, you should not have to modify the CMakeLists.txt.

I have just updated the code of one of our dependencies. Please update your copy.
I am able to compile on Ubuntu 16.04 (with gcc 5.4.0 and clang 6.0)

If you still have a problem, please post the output of `make VERBOSE=1` around the first error.
Thank you,
Boris.

**Comment by Jean-Baptiste-Camps** [comment]
Thanks on the quick reply ! Still having the problem, here is the output of verbose:

```
[ 79%] Building CXX object software/DocCreator/CMakeFiles/DocCreator.dir/src/FontGenerator/OCRDialog.cpp.o
cd /home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/build/software/DocCreator && /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/opencv -I/usr/local/include -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/libs/Lipsum4Qt/src -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/framework/src -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/build -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/build/software/DocCreator -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/lzham_codec/include -I/home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/Degradations/Distortion3DModel/thirdparty/eigen-3.3.4  -std=c++11 -Wall -Wextra -std=c++0x -O2 -g -DNDEBUG   -fPIC -o CMakeFiles/DocCreator.dir/src/FontGenerator/OCRDialog.cpp.o -c /home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/FontGenerator/OCRDialog.cpp
In file included from /usr/local/include/tesseract/ltrresultiterator.h:26:0,
                 from /usr/local/include/tesseract/resultiterator.h:26,
                 from /usr/local/include/tesseract/baseapi.h:31,
                 from /home/jbc/Data/F/LAKME/01_ocerisation/DocCreator/DocCreator/software/DocCreator/src/FontGenerator/OCRDialog.cpp:20:
/usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
   static string UTF32ToUTF8(const std::vector<char32>& str32);
          ^
software/DocCreator/CMakeFiles/DocCreator.dir/build.make:1826 : la recette pour la cible « software/DocCreator/CMakeFiles/DocCreator.dir/src/FontGenerator/OCRDialog.cpp.o » a échouée
make[2]: *** [software/DocCreator/CMakeFiles/DocCreator.dir/src/FontGenerator/OCRDialog.cpp.o] Erreur 1

```

**Comment by BorisMansencal** [comment]
Could you give me the output of the following commands: 
```
/usr/bin/c++ --version
pkg-config --modversion tesseract
pkg-config --modversion lept
pkg-config --cflags --libs tesseract
```

It seems that tesseract is installed in /usr/local. So, I guess this is not a packaged version and you have installed it from sources ?

**Comment by Jean-Baptiste-Camps** [comment]
Here it is :
```
$ /usr/bin/c++ --version
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ pkg-config --modversion tesseract
4.00.00dev
$ pkg-config --modversion lept
1.76.0
$ pkg-config --cflags --libs tesseract
-I/usr/local/include/tesseract -I/usr/include/leptonica -L/usr/local/lib -ltesseract
```
Actually, I have installed 4.0 from PPA, https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr, but I have also a compiled version somewhere to be used for training (inside the OCR-D-train folder).

**Comment by BorisMansencal** [comment]
I have not tried tesseract 4.0 from this PPA.
However, I have just compiled github master from https://github.com/tesseract-ocr/tesseract and it compiles fine on Ubuntu 16.04.
Several things you can try:
- revert the change to /usr/include/c++/v1/string (it is not needed as you are using GCC 5.4.0).
  and try to compile a simple C++ program test.cpp: 
```
#include <iostream>
#include <string>

int
main()
{
  std::string s="hello";
  std::cerr<<s<<std::endl;
  return 0;
}
```
with ```/usr/bin/c++ -Wall -std=c++11 test.cpp``` 
- If not already done, update your tesseract package. I see there is a quite recent version from 2018-06-15 on the PPA.
- Try to compile current git version of tesseract from sources:
```
git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
sudo apt-get install libtool automake autoconf-archive
./autogen.sh 
./configure
make 
sudo make install 
```

- Ultimately, you could try this (rather ugly) solution: add the following two lines before line 20 of DocCreator/software/DocCreator/src/FontGenerator/OCRDialog.cpp:
```
#include <string>
using namespace std;
```

**Comment by Jean-Baptiste-Camps** [comment]
Ok, apparently, there is a bug that is fixed in Github Tesseract but not in the ppa.
I think this is related to https://github.com/tesseract-ocr/tesseract/issues/1047 and https://github.com/tesseract-ocr/tesseract/issues/1045 Apparently, it has something to do with Google's coding conventions.

I tried what you suggested.

1. the simple CPP program compile and works fine;
2. I have updated to the latest available Tesseract from the PPA;

It still didn't worked after that. So, I went straight to the ugly solution, which didn't worked as such (it caused other errors).

So, along the same lines, I tried to add, before l. 20 of `DocCreator/software/DocCreator/src/FontGenerator/OCRDialog.cpp`,
```cpp
#include <string>
using std::string;
```
And then I had to add it as well in 
- `software/DocCreator/src/FontGenerator/StructureDetection.cpp` (l. 7);

And then it worked ! Now I'm all set to create artificial HTR data.
